### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by bdwain** [smacker/jasmine-expect-jsx#10]
Hi,
I noticed that there is a dependency on react even though it's not used directly. I believe it could be removed (react-element-to-jsx-string) already has a peer dependency. 

Also, react-element-to-jsx-string is on version 13 now. Is it possible to upgrade to use the latest version?

Thanks!

**Comment by smacker** [comment]
thank you for pointing out! I released v3.0.0 with new react-element-to-jsx-string and removed react from direct dependencies.

**Comment by bdwain** [comment]
Thanks!
