### ISSUE TITLE
new feature of react-element-to-jsx-string not being pulled in

### ISSUE THREAD

**Issue by bdwain** [smacker/jasmine-expect-jsx#11]
react-element-to-jsx-string recently [added fragment support](https://github.com/algolia/react-element-to-jsx-string/commit/768cce02206c52840761e901ba05ab3d46f7e1d0).

I tried to use it with jasmine-expect-jsx but it seems to not be used. I noticed that the generated bundle contains react-element-to-jsx-string's code rather than importing it. 

In the short term, would it be possible to upgrade dependencies and do a new release?

In the long term, I think switching to a rollup bundle that imported react-element-to-jsx-string would make it unnecessary to do a release every time they released. That could make it harder to make a bundle that runs in the browser though, so as an alternative there could be a post-install step that builds the bundle from whatever versions are currently in node modules.

**Comment by smacker** [comment]
If you use it in node or use any bundler you don't need to use generated bundle.

`require('jasmine-expect-jsx')` would import `index.js` which would import any version of `react-element-to-jsx-string > 13.0.0 and < 14.0.0`.

Though I just published v3.1.0 with new react-element-to-jsx-string in generated bundle for you.

**Comment by bdwain** [comment]
Thanks for releasing the new version!

I am using the karma plugin you wrote, https://github.com/smacker/karma-jasmine-expect-jsx, and that seems to pull in the dist file directly rather than importing it. So anyone using the karma helper would have the same problem I had and require this project to be released every time react-element-to-jsx-string is released. I also have a browser test runner that runs jasmine in the browser and pulls in the dist file directly, so something like that would also run into that problem.

What are your thoughts on building dist in a post-install script rather than committing it so that you didn't need to release this every time react-element-to-jsx-string updated? That would guarantee that at build time you had the latest copy of react-element-to-jsx-string. It slows down installation (and requires babel to be a dependency rather than a peer dependency) but I think it's the right way to solve this issue. The nature of this plugin means it's not going to be imported as part fo a bundle always so you need some pre-packaged working copy. If you're open to it, I'd be happy to make a PR.

**Comment by smacker** [comment]
Thanks for giving the context of your problem!

The idea of `dist` bundled file in this repository: you don't need anything, even npm, to use it. For example, you can just add
```html
<script src="https://raw.githubusercontent.com/smacker/jasmine-expect-jsx/master/dist/jasmine-expect-jsx.js">
```
in your test page with jasmine and it works. It's needed to be compatible with the simplest standalone jasmine mode.

And it does require publishing new version every time.

I see 2 possible solutions:
- Improve karma plugin. It uses `jasmine-expect-jsx/dist/jasmine-expect-jsx.js` now. But it can generate bundle on the fly with a cache somewhere. post-install is one of the options. It solves the problem when you use karma plugin.
- Add automatization (some script in travis or whatever) which would update react-element-to-jsx-string version, run tests and release a new version of jasmine-expect-jsx automatically when react-element-to-jsx-string is released. It solves the problem when you use karma plugin or you use it standalone.

I would be happy to merge PR with the implementation of any solution from above.

**Comment by bdwain** [comment]
Have you seen [greenkeeper](https://greenkeeper.io/)? It can auto-update your repo when dependencies update. It's free for public repos.

**Comment by smacker** [comment]
I knew about greenkeeper, but have never tried. Thanks for reminding, I've just enabled it for this repo.

**Comment by bdwain** [comment]
sweet!
