### ISSUE TITLE
1.1.0 dist fails on non ES6 browsers

### ISSUE THREAD

**Issue by gbabiars** [smacker/jasmine-expect-jsx#4]
Can you please bump the version to 1.1.1 and publish the update so that https://github.com/smacker/jasmine-expect-jsx/commit/326f865f5ecf252eaa5db0e7fcc5f6bc4fd88d5f is on npm?  Currently 1.1.0 fails on browsers that don't support shorthand object notation

**Comment by smacker** [comment]
done. sorry about that.
