### ISSUE TITLE
.not.toEqualJSX() not working with jest

### ISSUE THREAD

**Issue by Skotu** [smacker/jasmine-expect-jsx#5]
I managed to get jasmine-expect-jsx working, however I can see some strange behavior.

We have LoginPage component which renders simple div
```
<div className="LoginPage"></div>
```

I would like to check if that is what realy gets rendered.
```
renderer = createRenderer();
renderer.render(<LoginPage/>);
component = renderer.getRenderOutput();

const expected = <div className="LoginPage"></div>;
expect(component).toEqualJSX(expected);
```

And it is working fine. If i change the expected div class to something else
```
const expected = <div className="wrongClassName"></div>;
```

It's still working fine, i get nice output where i can see what is wrong. 

And now, when i try to do the same, but with negation using the .not.
```
const expected = <div className="LoginPage"></div>;
expect(component).not.toEqualJSX(expected);
```

I would expect it should fail, but the test still pases which is very weird. When i then change the classname for anything else i.e.
```
const expected = <div className="wrongClass"></div>;
expect(component).not.toEqualJSX(expected);
```

I got "No message was specified fo this matcher".

I am using Jest 19.0.2.
I've also tried enzyme shallow.debug() to get the output instead createRenderer() with the same result.

**Comment by smacker** [comment]
Fixed in 1.1.3
