### ISSUE TITLE
bug: es6 contained in es5 output

### ISSUE THREAD

**Issue by bdwain** [smacker/jasmine-expect-jsx#8]
i'm getting unexpected token > all over the place when including the newest jasmine-expect-jsx because the dist output seems to have fat arrows. 

for example, line 2418:

module.exports = object => {

it looks like it happened with the recent pr to update react-element-to-jsx-string but their output doesn't seem to contain any fat arrows.

**Comment by smacker** [comment]
Thank you for report. Yeah. v3 of stringify-object ships es6 code now. We didn't have problem with it because we use modern version of node.

I added babel transformation for dist output. Version 1.1.6 released.

**Comment by bdwain** [comment]
sweet thanks for fixing that so quickly.

**Comment by bdwain** [comment]
hi @smacker i think the issue still exists. a => is on line 570 of the dist output.

**Comment by smacker** [comment]
oh. babel doesn't use .babelrc when input comes from stdin. Fixed.

**Comment by bdwain** [comment]
thanks!
